version: "3.8"

services:
  db:
    image: postgres:15
    container_name: shop_db
    restart: always
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppassword
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
